[WIP] Support packages, repositories, exclude_packages in DataProc Spark jobs
yandex-cloud/python-sdk pull request #22
Opened 2021-12-07 12:57 UTC by Piatachock

Implement it in _wrapper, use it in examples

2021-12-08 10:45 UTC, Piatachock commented
* Add python-sdk `User-Agent` to all Channels in SDK; Support client-given user-agent, if any
* [DataProc] Support `packages`, `repositories`, `exclude_packages` in DataProc Spark jobs
* [DataProc] Improve examples

2021-12-08 12:53 UTC, MAnyKey requested changes

2021-12-08 12:53 UTC, MAnyKey commented on examples/dataproc/main.py
> +    parser.add_argument('--cluster-id', help='Existing cluster id')
Наверное стоит добавить 'if not provided the new cluster will be created'

2021-12-08 12:53 UTC, MAnyKey commented on yandexcloud/_channels.py
> +    def __init__(self, user_agent=None, **kwargs):
почему не использовать SDK_USER_AGENT как дефолт?

2021-12-08 12:53 UTC, MAnyKey commented on yandexcloud/_channels.py
> +            )
тут везде добавляются лишние диффы с переносом закрывающей скобки на новую строку.

2021-12-08 12:53 UTC, MAnyKey commented on yandexcloud/_sdk.py
> +        :param kwargs: Channels initialization parameters - see _channels.Channels
не уверен, что тут нужно именно ссылаться в _channels.Channels, потому что это внутренний объект.

2021-12-08 12:59 UTC, peter-volkov commented on examples/dataproc/main.py
> -        operation_result = create_cluster(sdk, create_cluster_request(arguments, resources=resources))
Тут надо не забывать, что это не только то, чем мы тестируем код, но и важная часть документации, преднагзначенная для пользователей.
Любое усложнение логики в примере нежелательно

2021-12-08 12:59 UTC, Piatachock commented on yandexcloud/_channels.py
> +    def __init__(self, user_agent=None, **kwargs):
SDK_USER_AGENT добавляется безусловно. Это - клиенсткий юзер-агент, он добавится в довесок к SDK-юзерагенту (который в свою очередь добавляется в довесок к grpc-lib-юзер-агенту)

2021-12-08 13:00 UTC, Piatachock commented on yandexcloud/_sdk.py
> +        :param kwargs: Channels initialization parameters - see _channels.Channels
Могу убрать обратно, просто сейчас посмотреть в Channels - единственный способ пользователю понять, что же можно передавать в kwargs

2021-12-08 13:10 UTC, Piatachock commented on examples/dataproc/main.py
> -        operation_result = create_cluster(sdk, create_cluster_request(arguments, resources=resources))
Резонно, удалил этот коммит

2021-12-08 13:10 UTC, Piatachock commented on examples/dataproc/main.py
> +    parser.add_argument('--cluster-id', help='Existing cluster id')
Удалил этот коммит

2021-12-08 13:13 UTC, Piatachock commented on yandexcloud/_channels.py
> +    def __init__(self, user_agent=None, **kwargs):
SDK_USER_AGENT используется безусловно - добавляется к дефолтному юзер-агенту, который проставляет либа grpc.
user_agent , принимаемый в __init__ - это возможность клиенту задать свой user-agent, который также добавится к дефолтному юзер-агенту SDK.

2021-12-08 13:31 UTC, peter-volkov reviewed
LGTM

2021-12-08 13:32 UTC, peter-volkov commented on yandexcloud/_channels.py
> +    def __init__(self, user_agent=None, **kwargs):
Можно назвать его тогда user_agent_suffix или вроде того, чтобы не путать

2021-12-08 13:36 UTC, Piatachock commented on yandexcloud/_channels.py
> +    def __init__(self, user_agent=None, **kwargs):
В докстринге есть пояснение, что это строка, которая препендит. Если этого недостаточно - я переназову переменную

2021-12-08 13:55 UTC, MAnyKey commented on yandexcloud/_sdk.py
> +        :param kwargs: Channels initialization parameters - see _channels.Channels
В идеале наверное стоит явно написать все используемые параметры и их описывать (но я не предлагаю делать это в текущем PR)

2021-12-08 13:57 UTC, Piatachock commented on yandexcloud/_sdk.py
> +        :param kwargs: Channels initialization parameters - see _channels.Channels
Пока оставить kwargs в докстринге? Или выпилить, как было до PR?

2021-12-09 09:56 UTC, MAnyKey commented on yandexcloud/_sdk.py
> +        :param kwargs: Channels initialization parameters - see _channels.Channels
давай пока оставим "Channels initialization parameters"

2021-12-09 10:12 UTC, Piatachock commented on yandexcloud/_sdk.py
> +        :param kwargs: Channels initialization parameters - see _channels.Channels
Выпилил

2021-12-09 10:12 UTC, Piatachock commented on yandexcloud/_channels.py
> +    def __init__(self, user_agent=None, **kwargs):
Переназвал в client_user_agent , чтобы была понятна разница с SDK_USER_AGENT

2021-12-09 10:47 UTC, Piatachock commented
@MAnyKey все замечания поправил

2021-12-10 13:26 UTC, merged