Support setting API endpoint based on zone from Metadata Service
yandex-cloud/python-sdk pull request #64
Opened 2023-02-16 12:36 UTC by s0neq

I hereby agree to the terms of the CLA available at: https://yandex.ru/legal/cla/?lang=en.

2023-02-16 12:39 UTC, Piatachock commented
LGTM

2023-02-17 12:22 UTC, l0kix2 requested changes
мне кажется сложновато и можно обойтись существующей опцией `endpoint`

@MAnyKey глянешь тоже?

2023-02-17 12:22 UTC, l0kix2 commented on README.md
> +sdk = yandexcloud.SDK(metadata_api_provider=True)
Меня смущает, что по сути это `sdk = yandexcloud.SDK(endpoint=get_endpoint_from_metadata())`, но мы 1) добавляем новый параметр 2) по названию совсем непонятно что это как-то связано с endpoint 3) никак не описано что будет если передать metadata_api_provider и endpoint. 4) название ключа metadata_api_provider ссылается на какой-то провайдер, который никак для пользователя недоступен и неясно почему он должен знать про такую сущность, это часть внутренней имплементации.

Может для простоты понимания мы просто предоставим хелпер `get_endpoint_from_metadata()` и предложим его передавать в endpoint?

2023-02-17 12:22 UTC, l0kix2 commented on yandexcloud/_auth_fabric.py
> +        super().__init__(get_endpoint_from_metadata())
Мне кажется не нужна иерархия классов чтобы хранить две строчки. На мой взгляд это оверинжиниринг.

2023-02-17 12:44 UTC, MAnyKey commented on yandexcloud/_auth_fabric.py
> +    if not zone.split("/")[-1].startswith("ru-"):
на самом деле не очень хороший критерий, при добавлении новых регионах придётся снова существенно менять код -- возможно тут просто "switch" по префиксам.

2024-03-07 10:27 UTC, closed without merging